//
//  SKResultSet.h
//  XXTExplorer
//
//  Stores a set of results generated by the parser.
//
//  Created by Zheng on 13/08/2017.
//  Copyright © 2017 Zheng. All rights reserved.
//

#import <Foundation/Foundation.h>

@class SKResult;

@interface SKResultSet : NSObject

// MARK: - Properties
@property (nonatomic, strong, readonly, getter=getResults) NSArray <SKResult *> *results;

/// Guaranteed to be larger or equal to the union of all the ranges
/// associated with the contained results.
@property (nonatomic, assign, readonly, getter=getRange) NSRange range;

// MARK: - Initializers
- (instancetype)initWithStartingRange:(NSRange)range;

// MARK: - Adding
- (void)extendWithRange:(NSRange)range;
- (void)addResult:(SKResult *)result;
- (void)addResultSet:(SKResultSet *)resultSet;

@end
