<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mod</string>
		<string>dat</string>
		<string>run</string>
	</array>
	<key>name</key>
	<string>AMPL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#argumentcurly</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#argumentbracket</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>argumentbracket</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w</string>
					<key>name</key>
					<string>meta.function-call.arguments.ampl</string>
				</dict>
			</array>
		</dict>
		<key>argumentcurly</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>meta.function-call.arguments.ampl</string>
				</dict>
			</array>
		</dict>
		<key>blockcomment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>contentName</key>
			<string>comment.block.documentation.ampl</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.slashstar.ampl</string>
		</dict>
		<key>doublequotestring</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ampl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ampl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.ampl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%(\w+%|\d+)</string>
					<key>name</key>
					<string>entity.name.class.ampl</string>
				</dict>
			</array>
		</dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#linecomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singlequotestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublequotestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#suffix</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#math</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(minimize|maximize|objective|coeff|coef|cover|obj|default|from|to|to_come|net_in|net_out|dimen|dimension|integer|binary|set|param|var|node|ordered|circular|reversed|symbolic|arc|check|close|display|drop|include|print|printf|quit|reset|restore|solve|update|write|shell|model|data|option|let|solution|fix|unfix|end|function|pipe|format|if|then|else|and|or|exists|forall|in|not|within|while|repeat|for|subject to|subj to|s\.t\.|card|next|nextw|prev|prevw|first|last|member|ord|ord0)\b</string>
			<key>name</key>
			<string>keyword.control.ampl</string>
		</dict>
		<key>linecomment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.gms</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#.*)(?!\[\[).*$\n?</string>
			<key>name</key>
			<string>comment.line.sharp.ampl</string>
		</dict>
		<key>math</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(union|diff|difference|symdiff|sum|inter|intersect|intersection|cross|setof|by|less|mod|div|product|abs|acos|acosh|alias|asin|asinh|atan|atan2|atanh|ceil|cos|exp|floor|log|log10|max|min|precision|round|sin|sinh|sqrt|tan|tanh|trunc|Beta|Cauchy|Exponential|Gamma|Irand224|Normal|Poisson|Uniform|Uniform01)\b</string>
			<key>name</key>
			<string>keyword.operator.ampl</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![\d.])\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?|(?i)([+-]?infinity)</string>
			<key>name</key>
			<string>constant.numeric.ampl</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>(\+|-|\*|\/|\*\*|=|&lt;=?|&gt;=?|==|\||\^|&lt;|&gt;|!|\.\.|:=|&amp;|!=|:|/)</string>
			<key>name</key>
			<string>keyword.operator.ampl</string>
		</dict>
		<key>singlequotestring</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.ampl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.ampl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.ampl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%(\w+%|\d+)</string>
					<key>name</key>
					<string>entity.name.class.ampl</string>
				</dict>
			</array>
		</dict>
		<key>suffix</key>
		<dict>
			<key>match</key>
			<string>\b\w*.(lb|ub|lb0|lb1|lb2|lrc|ub0|ub1|ub2|urc|val|lbs|ubs|init|body|dinit|dual|init0|ldual|slack|udual|lslack|uslack|dinit0)|(&lt;&lt;|&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.ampl</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ampl</string>
	<key>uuid</key>
	<string>7224acbd-b663-4ec3-8a02-3e6cf1680446</string>
</dict>
</plist>
