<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>capnp</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Cap’n Proto</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.struct.capnp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.capnp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(struct)(?:\s+([A-Za-z]+))?</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(using|import|union|enum|const|interface|annotation)\b</string>
			<key>name</key>
			<string>keyword.other.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:(Void|Bool|U?Int(8|16|32|64)|Float(32|64)|Text|Data|List\([.a-zA-Z0-9()]*\)|Object|union|group)</string>
			<key>name</key>
			<string>storage.type.builtin.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:[.a-zA-Z0-9()]+</string>
			<key>name</key>
			<string>storage.type.custom.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|void)\b</string>
			<key>name</key>
			<string>constant.language.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0x\h+|\d+(\.\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@0x\h+</string>
			<key>name</key>
			<string>constant.numeric.unique-id.capnp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\d+</string>
			<key>name</key>
			<string>constant.numeric.ordinal.capnp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.capnp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.capnp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.capnp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.capnp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.capnp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.begin.capnp</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.block.end.capnp</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{)(\})</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.capnp</string>
	<key>uuid</key>
	<string>57EA0128-2507-456B-AFF2-BEAFEB5A6B6E</string>
</dict>
</plist>
