<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ftl</string>
		<string>html</string>
	</array>
	<key>firstLineMatch</key>
	<string>&lt;/?#</string>
	<key>name</key>
	<string>FreeMarker</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>[\[|\&lt;]\#--</string>
			<key>end</key>
			<string>--[\&gt;|\]]</string>
			<key>name</key>
			<string>comment.block.ftl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;/?[@#]{1})\s*</string>
			<key>contentName</key>
			<string>source.ftl.tag.content</string>
			<key>end</key>
			<string>(\/?&gt;)</string>
			<key>name</key>
			<string>source.ftl.tag</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>built in directives</string>
					<key>match</key>
					<string>\b(if|else|elseif|switch|case|default|break|list|break|include|import|noparse|compress|escape|noescape|assign|global|local|setting|macro|nested|return|return|flush|stop|ftl|t|lt|rt|nt|attempt|recover|visit|recurse|fallback)\b</string>
					<key>name</key>
					<string>keyword.control.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var|assign)\b</string>
					<key>name</key>
					<string>storage.type.ftl</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.ftl</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.ftl</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>functions</string>
					<key>match</key>
					<string>\b(function)\s*(\w*)\b</string>
					<key>name</key>
					<string>meta.function.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?(number|string|boolean)</string>
					<key>name</key>
					<string>support.language.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+\.\w+</string>
					<key>name</key>
					<string>support.language.ftl</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.ftl</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Only really relates to &lt;@ ... &gt;</string>
					<key>match</key>
					<string>\b(\w*)=</string>
					<key>name</key>
					<string>variable.other.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(function)\b</string>
					<key>name</key>
					<string>function.ftl</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.ftl</string>
					<key>swallow</key>
					<string>\\.</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.ftl</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\$\w+</string>
							<key>name</key>
							<string>variable.other.tt.interpolated</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\$\{.*?\}</string>
							<key>name</key>
							<string>variable.other.tt.embedded</string>
						</dict>
					</array>
					<key>swallow</key>
					<string>\\.</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=|==|===|!=|!==|&amp;gt;|&amp;lt;|&amp;&amp;|\|\||\?\?</string>
					<key>name</key>
					<string>keyword.operator.assignment.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
					<key>name</key>
					<string>constant.numeric.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\btrue\b</string>
					<key>name</key>
					<string>constant.language.boolean.true.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfalse\b</string>
					<key>name</key>
					<string>constant.language.boolean.false.ftl</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bnull\b</string>
					<key>name</key>
					<string>constant.language.null.ftl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ftl</string>
	<key>uuid</key>
	<string>C011BB07-875D-4DEB-9582-0E1FEC0D1E4E</string>
</dict>
</plist>
