<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
TODO:  Command for copy original to untranslated, label as fuzzy, remove fuzzy, next fuzzy etc
Create meta scope for each entry
</string>
	<key>fileTypes</key>
	<array>
		<string>po</string>
		<string>potx</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~G</string>
	<key>name</key>
	<string>Gettext</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(?=(msgid(_plural)?|msgctxt)\s*"[^"])|^\s*$</string>
			<key>comment</key>
			<string>Start of body of document, after header</string>
			<key>end</key>
			<string>\z</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#body</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^msg(id|str)\s+""\s*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.po</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.po</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.po</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.po</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^"(?:([^\s:]+)(:)\s+)?([^"]*)"\s*$\n?</string>
			<key>name</key>
			<string>meta.header.po</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(msgid(_plural)?)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgid.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!")</string>
					<key>name</key>
					<string>meta.scope.msgid.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(\G|^)"</string>
							<key>end</key>
							<string>"</string>
							<key>name</key>
							<string>string.quoted.double.po</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\\[\\"]</string>
									<key>name</key>
									<string>constant.character.escape.po</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(msgstr)(?:(\[)(\d+)(\]))?\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgstr.po</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgstr.po</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.po</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgstr.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!")</string>
					<key>name</key>
					<string>meta.scope.msgstr.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(\G|^)"</string>
							<key>end</key>
							<string>"</string>
							<key>name</key>
							<string>string.quoted.double.po</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\\[\\"]</string>
									<key>name</key>
									<string>constant.character.escape.po</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(msgctxt)(?:(\[)(\d+)(\]))?\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgctxt.po</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgctxt.po</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.po</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.control.msgctxt.po</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!")</string>
					<key>name</key>
					<string>meta.scope.msgctxt.po</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(\G|^)"</string>
							<key>end</key>
							<string>"</string>
							<key>name</key>
							<string>string.quoted.double.po</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\\[\\"]</string>
									<key>name</key>
									<string>constant.character.escape.po</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.po</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(#~).*$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.obsolete.po</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>a line that does not begin with # or ". Could improve this regexp</string>
					<key>match</key>
					<string>^(?!\s*$)[^#"].*$\n?</string>
					<key>name</key>
					<string>invalid.illegal.po</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(?=#)</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(#,)\s+</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.po</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.flag.po</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.type.flag.po</string>
										</dict>
									</dict>
									<key>match</key>
									<string>(?:\G|,\s*)((?:fuzzy)|(?:no-)?(?:c|objc|sh|lisp|elisp|librep|scheme|smalltalk|java|csharp|awk|object-pascal|ycp|tcl|perl|perl-brace|php|gcc-internal|qt|boost)-format)</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>#\.</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.po</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.extracted.po</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(#:)[ \t]*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.po</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.reference.po</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(\S+:)([\d;]*)</string>
									<key>name</key>
									<string>storage.type.class.po</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>#\|</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.po</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.previous.po</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.po</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.po</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.po</string>
	<key>uuid</key>
	<string>F07730BD-59BC-41D0-AC3F-4AB2DCB6C54A</string>
</dict>
</plist>
