<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dlm</string>
	</array>
	<key>name</key>
	<string>IDL DLM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#header_keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#routine_declaration</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#structure_declaration</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.divider.idl-dlm</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#(=)\s*$\n</string>
					<key>name</key>
					<string>comment.line.banner.divider.idl-dlm</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.toc-list.banner.line.idl-dlm</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^#=\s*(.*?)\s*$\n?</string>
					<key>name</key>
					<string>comment.line.banner.idl-dlm</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?&lt;!\S)(?=#)(?!#\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.idl-dlm</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.idl-dlm</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.idl-dlm</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>header_keyword</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.toc-list.banner.line.idl-dlm</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.idl-dlm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Header keywords</string>
			<key>match</key>
			<string>(?i)\b(module|description|version|source|build_date|checksum)(.*)\b</string>
		</dict>
		<key>routine_declaration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.idl-dlm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.idl</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.idl</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.idl</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Routine declaration</string>
			<key>match</key>
			<string>(?i)^\s*(function|procedure)\s+([a-zA-Z0-9_$]+:?:?[a-zA-Z0-9_$]*)\s+([0-9]+)\s+([0-9]+|IDL_MAXPARAMS)\s+(((keywords|obsolete)\s+)*)</string>
		</dict>
		<key>structure_declaration</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.idl-dlm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.idl</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Structure declaration</string>
			<key>match</key>
			<string>(?i)^\s*(structure)\s+([a-zA-Z0-9_$]+)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.idl-dlm</string>
	<key>uuid</key>
	<string>7FC8175C-9E9A-49F0-B81E-A49C57775A7F</string>
</dict>
</plist>
