<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>idldoc</string>
	</array>
	<key>name</key>
	<string>IDLdoc file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>.*</string>
			<key>name</key>
			<string>comment.idl.idldoc</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.idl-idldoc</string>
	<key>uuid</key>
	<string>E18B4441-7323-45BF-B481-DA48DC11C65A</string>
</dict>
</plist>
