<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mu</string>
		<string>mush</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>MUSHCode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(")(.*)$</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#[0-9]+</string>
			<key>name</key>
			<string>entity.object.valid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#-[0-9]+</string>
			<key>name</key>
			<string>entity.object.invalid</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>=\$(.*):</string>
			<key>name</key>
			<string>keyword.syntax</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%[qzv]?[0-9a-zA-Z]</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%[#@?]</string>
			<key>name</key>
			<string>variable.substitution</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?=[A-Za-z_][A-Za-z0-9_]*\s*\()</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>name</key>
			<string>meta.function-call</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[A-Za-z_][A-Za-z0-9_]*)</string>
					<key>contentName</key>
					<string>entity.function</string>
					<key>end</key>
					<string>(?=\()</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#function_name</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.syntax</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.function-call.arguments</string>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.syntax</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#keyword_arguments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$base</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(@)([A-Za-z0-9.\_/]*)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\-?&amp;(?!api)([A-Za-z0-9]*[_.\-][A-Za-z0-9_\-./]*)</string>
			<key>name</key>
			<string>keyword.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\-?&amp;(?!api)([A-Za-z0-9.\_/\-]*)</string>
			<key>name</key>
			<string>keyword.attribute</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\-?&amp;([A-Za-z0-9.\_/\-]*)</string>
			<key>name</key>
			<string>keyword.api</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(-)</string>
			<key>name</key>
			<string>support.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.variable.directive.name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable.directive.value</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^# ([a-z])+: (.*)</string>
			<key>name</key>
			<string>support.variable.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(#).*</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[A-Za-z]+</string>
			<key>name</key>
			<string>support.alias</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\[\]\(\)\{\}]</string>
			<key>name</key>
			<string>keyword.syntax</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mushcode</string>
	<key>uuid</key>
	<string>FAAB0248-2138-4A88-AFDB-CD28D833AE19</string>
</dict>
</plist>
