<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>proto</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Protocol Buffers</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(default|enum|extend|extensions|message|option|optional|package|rpc|repeated|required|returns|service)\b</string>
			<key>name</key>
			<string>keyword.operator.proto</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-slash.proto</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.proto</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bool|bytes|double|fixed32|fixed64|float|int32|int64|sfixed32|sfixed64|sint32|sint64|string|uint32|uint64)\b</string>
			<key>name</key>
			<string>constant.language.proto</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(import)\s</string>
			<key>name</key>
			<string>keyword.control.import.proto</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.proto</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.proto</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-zA-Z0-9_\.]*?)\(</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.proto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.proto</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.proto</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.proto</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.proto</string>
	<key>uuid</key>
	<string>D6B0BFD2-F416-4E91-8C53-CD71EA3EE951</string>
</dict>
</plist>
