<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>svg</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(&lt;[^!?%/](?!.+?(/&gt;|&lt;/.+?&gt;))|&lt;[!%]--(?!.+?--%?&gt;)|&lt;%[!]?(?!.+?%&gt;))</string>
	<key>foldingStopMarker</key>
	<string>^\s*(&lt;/[^&gt;]+&gt;|[/%]&gt;|--&gt;)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>SVG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escaped.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:style))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.style.svg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/((?i:style))&gt;(?:\s*\n)?</string>
			<key>name</key>
			<string>source.css.embedded.svg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>&gt;</string>
					<key>end</key>
					<string>(?=&lt;/(?i:style))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:script))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.svg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(script))&gt;(?:\s*\n)?</string>
			<key>name</key>
			<string>source.js.embedded.svg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:script))&gt;</string>
					<key>end</key>
					<string>&lt;/((?i:script))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?&lt;((?i:handler))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.handler.svg</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(script))&gt;(?:\s*\n)?</string>
			<key>name</key>
			<string>source.js.embedded.svg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:handler))&gt;</string>
					<key>end</key>
					<string>&lt;/((?i:handler))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.xml.svg</string>
	<key>uuid</key>
	<string>60E1A653-2588-410D-8F89-9DA05E8BF163</string>
</dict>
</plist>
