<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>toml</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>TOML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#groups</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#key_pair</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#invalid</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.toml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.number-sign.toml</string>
				</dict>
			</array>
		</dict>
		<key>groups</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.begin.toml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[^\s.]+</string>
							<key>name</key>
							<string>entity.name.section.toml</string>
						</dict>
					</array>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.begin.toml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\[)([^\[\]]*)(\])</string>
			<key>name</key>
			<string>meta.group.toml</string>
		</dict>
		<key>invalid</key>
		<dict>
			<key>match</key>
			<string>\S+(\s*(?=\S))?</string>
			<key>name</key>
			<string>invalid.illegal.not-allowed-here.toml</string>
		</dict>
		<key>key_pair</key>
		<dict>
			<key>begin</key>
			<string>(\S+)\s*(=)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.toml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.toml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)(?&lt;!=)|$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#primatives</string>
				</dict>
			</array>
		</dict>
		<key>primatives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.toml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\([tnr"\\]|x\h\h)</string>
							<key>name</key>
							<string>constant.character.escape.toml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\G[0-9]{4}-(0[1-9]|1[012])-(?!00|3[2-9])[0-3][0-9]T[0-9]{2}:[0-9]{2}:[0-9]{2}Z</string>
					<key>name</key>
					<string>constant.other.date.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G(true|false)</string>
					<key>name</key>
					<string>constant.language.boolean.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G-?[0-9]+\.[0-9]+</string>
					<key>name</key>
					<string>constant.numeric.float.toml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\G-?[0-9]+</string>
					<key>name</key>
					<string>constant.numeric.integer.toml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\G\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.toml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.array.toml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?="|-?[0-9]|true|false|\[)</string>
							<key>end</key>
							<string>,|(?=])</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.array.toml</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#primatives</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comments</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#invalid</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#invalid</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.toml</string>
	<key>uuid</key>
	<string>7DEF2EDB-5BB7-4DD2-9E78-3541A26B7923</string>
</dict>
</plist>
